/*
 * 3DS OUTSCALE API
 *
 * Welcome to the OUTSCALE API documentation.<br /> The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br /> You can learn more about errors returned by the API in the dedicated [errors page](api/errors).<br /><br /> Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but there are [differences in resource names](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html) between AWS and the OUTSCALE API.<br /> You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.<br /><br /> An OpenAPI description of the OUTSCALE API is also available in this [GitHub repository](https://github.com/outscale/osc-api).
 *
 * API version: 1.26
 * Contact: support@outscale.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package osc

import (
	"encoding/json"
)

// UpdateVmTemplateResponse struct for UpdateVmTemplateResponse
type UpdateVmTemplateResponse struct {
	ResponseContext *ResponseContext `json:"ResponseContext,omitempty"`
	VmTemplate      *VmTemplate      `json:"VmTemplate,omitempty"`
}

// NewUpdateVmTemplateResponse instantiates a new UpdateVmTemplateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateVmTemplateResponse() *UpdateVmTemplateResponse {
	this := UpdateVmTemplateResponse{}
	return &this
}

// NewUpdateVmTemplateResponseWithDefaults instantiates a new UpdateVmTemplateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateVmTemplateResponseWithDefaults() *UpdateVmTemplateResponse {
	this := UpdateVmTemplateResponse{}
	return &this
}

// GetResponseContext returns the ResponseContext field value if set, zero value otherwise.
func (o *UpdateVmTemplateResponse) GetResponseContext() ResponseContext {
	if o == nil || o.ResponseContext == nil {
		var ret ResponseContext
		return ret
	}
	return *o.ResponseContext
}

// GetResponseContextOk returns a tuple with the ResponseContext field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateVmTemplateResponse) GetResponseContextOk() (*ResponseContext, bool) {
	if o == nil || o.ResponseContext == nil {
		return nil, false
	}
	return o.ResponseContext, true
}

// HasResponseContext returns a boolean if a field has been set.
func (o *UpdateVmTemplateResponse) HasResponseContext() bool {
	if o != nil && o.ResponseContext != nil {
		return true
	}

	return false
}

// SetResponseContext gets a reference to the given ResponseContext and assigns it to the ResponseContext field.
func (o *UpdateVmTemplateResponse) SetResponseContext(v ResponseContext) {
	o.ResponseContext = &v
}

// GetVmTemplate returns the VmTemplate field value if set, zero value otherwise.
func (o *UpdateVmTemplateResponse) GetVmTemplate() VmTemplate {
	if o == nil || o.VmTemplate == nil {
		var ret VmTemplate
		return ret
	}
	return *o.VmTemplate
}

// GetVmTemplateOk returns a tuple with the VmTemplate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateVmTemplateResponse) GetVmTemplateOk() (*VmTemplate, bool) {
	if o == nil || o.VmTemplate == nil {
		return nil, false
	}
	return o.VmTemplate, true
}

// HasVmTemplate returns a boolean if a field has been set.
func (o *UpdateVmTemplateResponse) HasVmTemplate() bool {
	if o != nil && o.VmTemplate != nil {
		return true
	}

	return false
}

// SetVmTemplate gets a reference to the given VmTemplate and assigns it to the VmTemplate field.
func (o *UpdateVmTemplateResponse) SetVmTemplate(v VmTemplate) {
	o.VmTemplate = &v
}

func (o UpdateVmTemplateResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ResponseContext != nil {
		toSerialize["ResponseContext"] = o.ResponseContext
	}
	if o.VmTemplate != nil {
		toSerialize["VmTemplate"] = o.VmTemplate
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateVmTemplateResponse struct {
	value *UpdateVmTemplateResponse
	isSet bool
}

func (v NullableUpdateVmTemplateResponse) Get() *UpdateVmTemplateResponse {
	return v.value
}

func (v *NullableUpdateVmTemplateResponse) Set(val *UpdateVmTemplateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateVmTemplateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateVmTemplateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateVmTemplateResponse(val *UpdateVmTemplateResponse) *NullableUpdateVmTemplateResponse {
	return &NullableUpdateVmTemplateResponse{value: val, isSet: true}
}

func (v NullableUpdateVmTemplateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateVmTemplateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
