/*
 * 3DS OUTSCALE API
 *
 * Welcome to the OUTSCALE API documentation.<br /> The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br /> You can learn more about errors returned by the API in the dedicated [errors page](api/errors).<br /><br /> Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but there are [differences in resource names](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html) between AWS and the OUTSCALE API.<br /> You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.<br /><br /> An OpenAPI description of the OUTSCALE API is also available in this [GitHub repository](https://github.com/outscale/osc-api).
 *
 * API version: 1.26
 * Contact: support@outscale.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package osc

import (
	"encoding/json"
)

// DeleteVmGroupRequest struct for DeleteVmGroupRequest
type DeleteVmGroupRequest struct {
	// If true, checks whether you have the required permissions to perform the action.
	DryRun *bool `json:"DryRun,omitempty"`
	// The ID of the VM group you want to delete.
	VmGroupId string `json:"VmGroupId"`
}

// NewDeleteVmGroupRequest instantiates a new DeleteVmGroupRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteVmGroupRequest(vmGroupId string) *DeleteVmGroupRequest {
	this := DeleteVmGroupRequest{}
	this.VmGroupId = vmGroupId
	return &this
}

// NewDeleteVmGroupRequestWithDefaults instantiates a new DeleteVmGroupRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteVmGroupRequestWithDefaults() *DeleteVmGroupRequest {
	this := DeleteVmGroupRequest{}
	return &this
}

// GetDryRun returns the DryRun field value if set, zero value otherwise.
func (o *DeleteVmGroupRequest) GetDryRun() bool {
	if o == nil || o.DryRun == nil {
		var ret bool
		return ret
	}
	return *o.DryRun
}

// GetDryRunOk returns a tuple with the DryRun field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteVmGroupRequest) GetDryRunOk() (*bool, bool) {
	if o == nil || o.DryRun == nil {
		return nil, false
	}
	return o.DryRun, true
}

// HasDryRun returns a boolean if a field has been set.
func (o *DeleteVmGroupRequest) HasDryRun() bool {
	if o != nil && o.DryRun != nil {
		return true
	}

	return false
}

// SetDryRun gets a reference to the given bool and assigns it to the DryRun field.
func (o *DeleteVmGroupRequest) SetDryRun(v bool) {
	o.DryRun = &v
}

// GetVmGroupId returns the VmGroupId field value
func (o *DeleteVmGroupRequest) GetVmGroupId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VmGroupId
}

// GetVmGroupIdOk returns a tuple with the VmGroupId field value
// and a boolean to check if the value has been set.
func (o *DeleteVmGroupRequest) GetVmGroupIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VmGroupId, true
}

// SetVmGroupId sets field value
func (o *DeleteVmGroupRequest) SetVmGroupId(v string) {
	o.VmGroupId = v
}

func (o DeleteVmGroupRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.DryRun != nil {
		toSerialize["DryRun"] = o.DryRun
	}
	if true {
		toSerialize["VmGroupId"] = o.VmGroupId
	}
	return json.Marshal(toSerialize)
}

type NullableDeleteVmGroupRequest struct {
	value *DeleteVmGroupRequest
	isSet bool
}

func (v NullableDeleteVmGroupRequest) Get() *DeleteVmGroupRequest {
	return v.value
}

func (v *NullableDeleteVmGroupRequest) Set(val *DeleteVmGroupRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteVmGroupRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteVmGroupRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteVmGroupRequest(val *DeleteVmGroupRequest) *NullableDeleteVmGroupRequest {
	return &NullableDeleteVmGroupRequest{value: val, isSet: true}
}

func (v NullableDeleteVmGroupRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteVmGroupRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
