// Code generated by ifacemaker; DO NOT EDIT.

package osc

import (
	"context"
	"io"

	"github.com/outscale/osc-sdk-go/v3/internal/middleware"
)

// Interface ...
type Interface interface {
	// AcceptNetPeeringWithBody request with arbitrary body returning *AcceptNetPeeringResponse
	AcceptNetPeeringWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*AcceptNetPeeringResponse, error)
	AcceptNetPeering(ctx context.Context, body AcceptNetPeeringJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*AcceptNetPeeringResponse, error)
	// AddUserToUserGroupWithBody request with arbitrary body returning *AddUserToUserGroupResponse
	AddUserToUserGroupWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*AddUserToUserGroupResponse, error)
	AddUserToUserGroup(ctx context.Context, body AddUserToUserGroupJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*AddUserToUserGroupResponse, error)
	// CheckAuthenticationWithBody request with arbitrary body returning *CheckAuthenticationResponse
	CheckAuthenticationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CheckAuthenticationResponse, error)
	CheckAuthentication(ctx context.Context, body CheckAuthenticationJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CheckAuthenticationResponse, error)
	// CreateAccessKeyWithBody request with arbitrary body returning *CreateAccessKeyResponse
	CreateAccessKeyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateAccessKeyResponse, error)
	CreateAccessKey(ctx context.Context, body CreateAccessKeyJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateAccessKeyResponse, error)
	// CreateAccountWithBody request with arbitrary body returning *CreateAccountResponse
	CreateAccountWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateAccountResponse, error)
	CreateAccount(ctx context.Context, body CreateAccountJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateAccountResponse, error)
	// CreateApiAccessRuleWithBody request with arbitrary body returning *CreateApiAccessRuleResponse
	CreateApiAccessRuleWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateApiAccessRuleResponse, error)
	CreateApiAccessRule(ctx context.Context, body CreateApiAccessRuleJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateApiAccessRuleResponse, error)
	// CreateCaWithBody request with arbitrary body returning *CreateCaResponse
	CreateCaWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateCaResponse, error)
	CreateCa(ctx context.Context, body CreateCaJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateCaResponse, error)
	// CreateClientGatewayWithBody request with arbitrary body returning *CreateClientGatewayResponse
	CreateClientGatewayWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateClientGatewayResponse, error)
	CreateClientGateway(ctx context.Context, body CreateClientGatewayJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateClientGatewayResponse, error)
	// CreateDedicatedGroupWithBody request with arbitrary body returning *CreateDedicatedGroupResponse
	CreateDedicatedGroupWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateDedicatedGroupResponse, error)
	CreateDedicatedGroup(ctx context.Context, body CreateDedicatedGroupJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateDedicatedGroupResponse, error)
	// CreateDhcpOptionsWithBody request with arbitrary body returning *CreateDhcpOptionsResponse
	CreateDhcpOptionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateDhcpOptionsResponse, error)
	CreateDhcpOptions(ctx context.Context, body CreateDhcpOptionsJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateDhcpOptionsResponse, error)
	// CreateDirectLinkWithBody request with arbitrary body returning *CreateDirectLinkResponse
	CreateDirectLinkWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateDirectLinkResponse, error)
	CreateDirectLink(ctx context.Context, body CreateDirectLinkJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateDirectLinkResponse, error)
	// CreateDirectLinkInterfaceWithBody request with arbitrary body returning *CreateDirectLinkInterfaceResponse
	CreateDirectLinkInterfaceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateDirectLinkInterfaceResponse, error)
	CreateDirectLinkInterface(ctx context.Context, body CreateDirectLinkInterfaceJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateDirectLinkInterfaceResponse, error)
	// CreateFlexibleGpuWithBody request with arbitrary body returning *CreateFlexibleGpuResponse
	CreateFlexibleGpuWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateFlexibleGpuResponse, error)
	CreateFlexibleGpu(ctx context.Context, body CreateFlexibleGpuJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateFlexibleGpuResponse, error)
	// CreateImageWithBody request with arbitrary body returning *CreateImageResponse
	CreateImageWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateImageResponse, error)
	CreateImage(ctx context.Context, body CreateImageJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateImageResponse, error)
	// CreateImageExportTaskWithBody request with arbitrary body returning *CreateImageExportTaskResponse
	CreateImageExportTaskWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateImageExportTaskResponse, error)
	CreateImageExportTask(ctx context.Context, body CreateImageExportTaskJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateImageExportTaskResponse, error)
	// CreateInternetServiceWithBody request with arbitrary body returning *CreateInternetServiceResponse
	CreateInternetServiceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateInternetServiceResponse, error)
	CreateInternetService(ctx context.Context, body CreateInternetServiceJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateInternetServiceResponse, error)
	// CreateKeypairWithBody request with arbitrary body returning *CreateKeypairResponse
	CreateKeypairWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateKeypairResponse, error)
	CreateKeypair(ctx context.Context, body CreateKeypairJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateKeypairResponse, error)
	// CreateListenerRuleWithBody request with arbitrary body returning *CreateListenerRuleResponse
	CreateListenerRuleWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateListenerRuleResponse, error)
	CreateListenerRule(ctx context.Context, body CreateListenerRuleJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateListenerRuleResponse, error)
	// CreateLoadBalancerWithBody request with arbitrary body returning *CreateLoadBalancerResponse
	CreateLoadBalancerWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateLoadBalancerResponse, error)
	CreateLoadBalancer(ctx context.Context, body CreateLoadBalancerJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateLoadBalancerResponse, error)
	// CreateLoadBalancerListenersWithBody request with arbitrary body returning *CreateLoadBalancerListenersResponse
	CreateLoadBalancerListenersWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateLoadBalancerListenersResponse, error)
	CreateLoadBalancerListeners(ctx context.Context, body CreateLoadBalancerListenersJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateLoadBalancerListenersResponse, error)
	// CreateLoadBalancerPolicyWithBody request with arbitrary body returning *CreateLoadBalancerPolicyResponse
	CreateLoadBalancerPolicyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateLoadBalancerPolicyResponse, error)
	CreateLoadBalancerPolicy(ctx context.Context, body CreateLoadBalancerPolicyJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateLoadBalancerPolicyResponse, error)
	// CreateLoadBalancerTagsWithBody request with arbitrary body returning *CreateLoadBalancerTagsResponse
	CreateLoadBalancerTagsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateLoadBalancerTagsResponse, error)
	CreateLoadBalancerTags(ctx context.Context, body CreateLoadBalancerTagsJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateLoadBalancerTagsResponse, error)
	// CreateNatServiceWithBody request with arbitrary body returning *CreateNatServiceResponse
	CreateNatServiceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateNatServiceResponse, error)
	CreateNatService(ctx context.Context, body CreateNatServiceJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateNatServiceResponse, error)
	// CreateNetWithBody request with arbitrary body returning *CreateNetResponse
	CreateNetWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateNetResponse, error)
	CreateNet(ctx context.Context, body CreateNetJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateNetResponse, error)
	// CreateNetAccessPointWithBody request with arbitrary body returning *CreateNetAccessPointResponse
	CreateNetAccessPointWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateNetAccessPointResponse, error)
	CreateNetAccessPoint(ctx context.Context, body CreateNetAccessPointJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateNetAccessPointResponse, error)
	// CreateNetPeeringWithBody request with arbitrary body returning *CreateNetPeeringResponse
	CreateNetPeeringWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateNetPeeringResponse, error)
	CreateNetPeering(ctx context.Context, body CreateNetPeeringJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateNetPeeringResponse, error)
	// CreateNicWithBody request with arbitrary body returning *CreateNicResponse
	CreateNicWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateNicResponse, error)
	CreateNic(ctx context.Context, body CreateNicJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateNicResponse, error)
	// CreatePolicyWithBody request with arbitrary body returning *CreatePolicyResponse
	CreatePolicyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreatePolicyResponse, error)
	CreatePolicy(ctx context.Context, body CreatePolicyJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreatePolicyResponse, error)
	// CreatePolicyVersionWithBody request with arbitrary body returning *CreatePolicyVersionResponse
	CreatePolicyVersionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreatePolicyVersionResponse, error)
	CreatePolicyVersion(ctx context.Context, body CreatePolicyVersionJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreatePolicyVersionResponse, error)
	// CreateProductTypeWithBody request with arbitrary body returning *CreateProductTypeResponse
	CreateProductTypeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateProductTypeResponse, error)
	CreateProductType(ctx context.Context, body CreateProductTypeJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateProductTypeResponse, error)
	// CreatePublicIpWithBody request with arbitrary body returning *CreatePublicIpResponse
	CreatePublicIpWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreatePublicIpResponse, error)
	CreatePublicIp(ctx context.Context, body CreatePublicIpJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreatePublicIpResponse, error)
	// CreateRouteWithBody request with arbitrary body returning *CreateRouteResponse
	CreateRouteWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateRouteResponse, error)
	CreateRoute(ctx context.Context, body CreateRouteJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateRouteResponse, error)
	// CreateRouteTableWithBody request with arbitrary body returning *CreateRouteTableResponse
	CreateRouteTableWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateRouteTableResponse, error)
	CreateRouteTable(ctx context.Context, body CreateRouteTableJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateRouteTableResponse, error)
	// CreateSecurityGroupWithBody request with arbitrary body returning *CreateSecurityGroupResponse
	CreateSecurityGroupWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateSecurityGroupResponse, error)
	CreateSecurityGroup(ctx context.Context, body CreateSecurityGroupJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateSecurityGroupResponse, error)
	// CreateSecurityGroupRuleWithBody request with arbitrary body returning *CreateSecurityGroupRuleResponse
	CreateSecurityGroupRuleWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateSecurityGroupRuleResponse, error)
	CreateSecurityGroupRule(ctx context.Context, body CreateSecurityGroupRuleJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateSecurityGroupRuleResponse, error)
	// CreateServerCertificateWithBody request with arbitrary body returning *CreateServerCertificateResponse
	CreateServerCertificateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateServerCertificateResponse, error)
	CreateServerCertificate(ctx context.Context, body CreateServerCertificateJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateServerCertificateResponse, error)
	// CreateSnapshotWithBody request with arbitrary body returning *CreateSnapshotResponse
	CreateSnapshotWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateSnapshotResponse, error)
	CreateSnapshot(ctx context.Context, body CreateSnapshotJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateSnapshotResponse, error)
	// CreateSnapshotExportTaskWithBody request with arbitrary body returning *CreateSnapshotExportTaskResponse
	CreateSnapshotExportTaskWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateSnapshotExportTaskResponse, error)
	CreateSnapshotExportTask(ctx context.Context, body CreateSnapshotExportTaskJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateSnapshotExportTaskResponse, error)
	// CreateSubnetWithBody request with arbitrary body returning *CreateSubnetResponse
	CreateSubnetWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateSubnetResponse, error)
	CreateSubnet(ctx context.Context, body CreateSubnetJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateSubnetResponse, error)
	// CreateTagsWithBody request with arbitrary body returning *CreateTagsResponse
	CreateTagsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateTagsResponse, error)
	CreateTags(ctx context.Context, body CreateTagsJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateTagsResponse, error)
	// CreateUserWithBody request with arbitrary body returning *CreateUserResponse
	CreateUserWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateUserResponse, error)
	CreateUser(ctx context.Context, body CreateUserJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateUserResponse, error)
	// CreateUserGroupWithBody request with arbitrary body returning *CreateUserGroupResponse
	CreateUserGroupWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateUserGroupResponse, error)
	CreateUserGroup(ctx context.Context, body CreateUserGroupJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateUserGroupResponse, error)
	// CreateVirtualGatewayWithBody request with arbitrary body returning *CreateVirtualGatewayResponse
	CreateVirtualGatewayWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateVirtualGatewayResponse, error)
	CreateVirtualGateway(ctx context.Context, body CreateVirtualGatewayJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateVirtualGatewayResponse, error)
	// CreateVmGroupWithBody request with arbitrary body returning *CreateVmGroupResponse
	CreateVmGroupWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateVmGroupResponse, error)
	CreateVmGroup(ctx context.Context, body CreateVmGroupJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateVmGroupResponse, error)
	// CreateVmTemplateWithBody request with arbitrary body returning *CreateVmTemplateResponse
	CreateVmTemplateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateVmTemplateResponse, error)
	CreateVmTemplate(ctx context.Context, body CreateVmTemplateJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateVmTemplateResponse, error)
	// CreateVmsWithBody request with arbitrary body returning *CreateVmsResponse
	CreateVmsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateVmsResponse, error)
	CreateVms(ctx context.Context, body CreateVmsJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateVmsResponse, error)
	// CreateVolumeWithBody request with arbitrary body returning *CreateVolumeResponse
	CreateVolumeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateVolumeResponse, error)
	CreateVolume(ctx context.Context, body CreateVolumeJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateVolumeResponse, error)
	// CreateVpnConnectionWithBody request with arbitrary body returning *CreateVpnConnectionResponse
	CreateVpnConnectionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateVpnConnectionResponse, error)
	CreateVpnConnection(ctx context.Context, body CreateVpnConnectionJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateVpnConnectionResponse, error)
	// CreateVpnConnectionRouteWithBody request with arbitrary body returning *CreateVpnConnectionRouteResponse
	CreateVpnConnectionRouteWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*CreateVpnConnectionRouteResponse, error)
	CreateVpnConnectionRoute(ctx context.Context, body CreateVpnConnectionRouteJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*CreateVpnConnectionRouteResponse, error)
	// DeleteAccessKeyWithBody request with arbitrary body returning *DeleteAccessKeyResponse
	DeleteAccessKeyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteAccessKeyResponse, error)
	DeleteAccessKey(ctx context.Context, body DeleteAccessKeyJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteAccessKeyResponse, error)
	// DeleteApiAccessRuleWithBody request with arbitrary body returning *DeleteApiAccessRuleResponse
	DeleteApiAccessRuleWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteApiAccessRuleResponse, error)
	DeleteApiAccessRule(ctx context.Context, body DeleteApiAccessRuleJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteApiAccessRuleResponse, error)
	// DeleteCaWithBody request with arbitrary body returning *DeleteCaResponse
	DeleteCaWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteCaResponse, error)
	DeleteCa(ctx context.Context, body DeleteCaJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteCaResponse, error)
	// DeleteClientGatewayWithBody request with arbitrary body returning *DeleteClientGatewayResponse
	DeleteClientGatewayWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteClientGatewayResponse, error)
	DeleteClientGateway(ctx context.Context, body DeleteClientGatewayJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteClientGatewayResponse, error)
	// DeleteDedicatedGroupWithBody request with arbitrary body returning *DeleteDedicatedGroupResponse
	DeleteDedicatedGroupWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteDedicatedGroupResponse, error)
	DeleteDedicatedGroup(ctx context.Context, body DeleteDedicatedGroupJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteDedicatedGroupResponse, error)
	// DeleteDhcpOptionsWithBody request with arbitrary body returning *DeleteDhcpOptionsResponse
	DeleteDhcpOptionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteDhcpOptionsResponse, error)
	DeleteDhcpOptions(ctx context.Context, body DeleteDhcpOptionsJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteDhcpOptionsResponse, error)
	// DeleteDirectLinkWithBody request with arbitrary body returning *DeleteDirectLinkResponse
	DeleteDirectLinkWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteDirectLinkResponse, error)
	DeleteDirectLink(ctx context.Context, body DeleteDirectLinkJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteDirectLinkResponse, error)
	// DeleteDirectLinkInterfaceWithBody request with arbitrary body returning *DeleteDirectLinkInterfaceResponse
	DeleteDirectLinkInterfaceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteDirectLinkInterfaceResponse, error)
	DeleteDirectLinkInterface(ctx context.Context, body DeleteDirectLinkInterfaceJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteDirectLinkInterfaceResponse, error)
	// DeleteExportTaskWithBody request with arbitrary body returning *DeleteExportTaskResponse
	DeleteExportTaskWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteExportTaskResponse, error)
	DeleteExportTask(ctx context.Context, body DeleteExportTaskJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteExportTaskResponse, error)
	// DeleteFlexibleGpuWithBody request with arbitrary body returning *DeleteFlexibleGpuResponse
	DeleteFlexibleGpuWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteFlexibleGpuResponse, error)
	DeleteFlexibleGpu(ctx context.Context, body DeleteFlexibleGpuJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteFlexibleGpuResponse, error)
	// DeleteImageWithBody request with arbitrary body returning *DeleteImageResponse
	DeleteImageWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteImageResponse, error)
	DeleteImage(ctx context.Context, body DeleteImageJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteImageResponse, error)
	// DeleteInternetServiceWithBody request with arbitrary body returning *DeleteInternetServiceResponse
	DeleteInternetServiceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteInternetServiceResponse, error)
	DeleteInternetService(ctx context.Context, body DeleteInternetServiceJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteInternetServiceResponse, error)
	// DeleteKeypairWithBody request with arbitrary body returning *DeleteKeypairResponse
	DeleteKeypairWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteKeypairResponse, error)
	DeleteKeypair(ctx context.Context, body DeleteKeypairJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteKeypairResponse, error)
	// DeleteListenerRuleWithBody request with arbitrary body returning *DeleteListenerRuleResponse
	DeleteListenerRuleWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteListenerRuleResponse, error)
	DeleteListenerRule(ctx context.Context, body DeleteListenerRuleJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteListenerRuleResponse, error)
	// DeleteLoadBalancerWithBody request with arbitrary body returning *DeleteLoadBalancerResponse
	DeleteLoadBalancerWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteLoadBalancerResponse, error)
	DeleteLoadBalancer(ctx context.Context, body DeleteLoadBalancerJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteLoadBalancerResponse, error)
	// DeleteLoadBalancerListenersWithBody request with arbitrary body returning *DeleteLoadBalancerListenersResponse
	DeleteLoadBalancerListenersWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteLoadBalancerListenersResponse, error)
	DeleteLoadBalancerListeners(ctx context.Context, body DeleteLoadBalancerListenersJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteLoadBalancerListenersResponse, error)
	// DeleteLoadBalancerPolicyWithBody request with arbitrary body returning *DeleteLoadBalancerPolicyResponse
	DeleteLoadBalancerPolicyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteLoadBalancerPolicyResponse, error)
	DeleteLoadBalancerPolicy(ctx context.Context, body DeleteLoadBalancerPolicyJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteLoadBalancerPolicyResponse, error)
	// DeleteLoadBalancerTagsWithBody request with arbitrary body returning *DeleteLoadBalancerTagsResponse
	DeleteLoadBalancerTagsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteLoadBalancerTagsResponse, error)
	DeleteLoadBalancerTags(ctx context.Context, body DeleteLoadBalancerTagsJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteLoadBalancerTagsResponse, error)
	// DeleteNatServiceWithBody request with arbitrary body returning *DeleteNatServiceResponse
	DeleteNatServiceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteNatServiceResponse, error)
	DeleteNatService(ctx context.Context, body DeleteNatServiceJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteNatServiceResponse, error)
	// DeleteNetWithBody request with arbitrary body returning *DeleteNetResponse
	DeleteNetWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteNetResponse, error)
	DeleteNet(ctx context.Context, body DeleteNetJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteNetResponse, error)
	// DeleteNetAccessPointWithBody request with arbitrary body returning *DeleteNetAccessPointResponse
	DeleteNetAccessPointWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteNetAccessPointResponse, error)
	DeleteNetAccessPoint(ctx context.Context, body DeleteNetAccessPointJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteNetAccessPointResponse, error)
	// DeleteNetPeeringWithBody request with arbitrary body returning *DeleteNetPeeringResponse
	DeleteNetPeeringWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteNetPeeringResponse, error)
	DeleteNetPeering(ctx context.Context, body DeleteNetPeeringJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteNetPeeringResponse, error)
	// DeleteNicWithBody request with arbitrary body returning *DeleteNicResponse
	DeleteNicWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteNicResponse, error)
	DeleteNic(ctx context.Context, body DeleteNicJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteNicResponse, error)
	// DeletePolicyWithBody request with arbitrary body returning *DeletePolicyResponse
	DeletePolicyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeletePolicyResponse, error)
	DeletePolicy(ctx context.Context, body DeletePolicyJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeletePolicyResponse, error)
	// DeletePolicyVersionWithBody request with arbitrary body returning *DeletePolicyVersionResponse
	DeletePolicyVersionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeletePolicyVersionResponse, error)
	DeletePolicyVersion(ctx context.Context, body DeletePolicyVersionJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeletePolicyVersionResponse, error)
	// DeleteProductTypeWithBody request with arbitrary body returning *DeleteProductTypeResponse
	DeleteProductTypeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteProductTypeResponse, error)
	DeleteProductType(ctx context.Context, body DeleteProductTypeJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteProductTypeResponse, error)
	// DeletePublicIpWithBody request with arbitrary body returning *DeletePublicIpResponse
	DeletePublicIpWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeletePublicIpResponse, error)
	DeletePublicIp(ctx context.Context, body DeletePublicIpJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeletePublicIpResponse, error)
	// DeleteRouteWithBody request with arbitrary body returning *DeleteRouteResponse
	DeleteRouteWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteRouteResponse, error)
	DeleteRoute(ctx context.Context, body DeleteRouteJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteRouteResponse, error)
	// DeleteRouteTableWithBody request with arbitrary body returning *DeleteRouteTableResponse
	DeleteRouteTableWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteRouteTableResponse, error)
	DeleteRouteTable(ctx context.Context, body DeleteRouteTableJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteRouteTableResponse, error)
	// DeleteSecurityGroupWithBody request with arbitrary body returning *DeleteSecurityGroupResponse
	DeleteSecurityGroupWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteSecurityGroupResponse, error)
	DeleteSecurityGroup(ctx context.Context, body DeleteSecurityGroupJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteSecurityGroupResponse, error)
	// DeleteSecurityGroupRuleWithBody request with arbitrary body returning *DeleteSecurityGroupRuleResponse
	DeleteSecurityGroupRuleWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteSecurityGroupRuleResponse, error)
	DeleteSecurityGroupRule(ctx context.Context, body DeleteSecurityGroupRuleJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteSecurityGroupRuleResponse, error)
	// DeleteServerCertificateWithBody request with arbitrary body returning *DeleteServerCertificateResponse
	DeleteServerCertificateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteServerCertificateResponse, error)
	DeleteServerCertificate(ctx context.Context, body DeleteServerCertificateJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteServerCertificateResponse, error)
	// DeleteSnapshotWithBody request with arbitrary body returning *DeleteSnapshotResponse
	DeleteSnapshotWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteSnapshotResponse, error)
	DeleteSnapshot(ctx context.Context, body DeleteSnapshotJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteSnapshotResponse, error)
	// DeleteSubnetWithBody request with arbitrary body returning *DeleteSubnetResponse
	DeleteSubnetWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteSubnetResponse, error)
	DeleteSubnet(ctx context.Context, body DeleteSubnetJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteSubnetResponse, error)
	// DeleteTagsWithBody request with arbitrary body returning *DeleteTagsResponse
	DeleteTagsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteTagsResponse, error)
	DeleteTags(ctx context.Context, body DeleteTagsJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteTagsResponse, error)
	// DeleteUserWithBody request with arbitrary body returning *DeleteUserResponse
	DeleteUserWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteUserResponse, error)
	DeleteUser(ctx context.Context, body DeleteUserJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteUserResponse, error)
	// DeleteUserGroupWithBody request with arbitrary body returning *DeleteUserGroupResponse
	DeleteUserGroupWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteUserGroupResponse, error)
	DeleteUserGroup(ctx context.Context, body DeleteUserGroupJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteUserGroupResponse, error)
	// DeleteUserGroupPolicyWithBody request with arbitrary body returning *DeleteUserGroupPolicyResponse
	DeleteUserGroupPolicyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteUserGroupPolicyResponse, error)
	DeleteUserGroupPolicy(ctx context.Context, body DeleteUserGroupPolicyJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteUserGroupPolicyResponse, error)
	// DeleteUserPolicyWithBody request with arbitrary body returning *DeleteUserPolicyResponse
	DeleteUserPolicyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteUserPolicyResponse, error)
	DeleteUserPolicy(ctx context.Context, body DeleteUserPolicyJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteUserPolicyResponse, error)
	// DeleteVirtualGatewayWithBody request with arbitrary body returning *DeleteVirtualGatewayResponse
	DeleteVirtualGatewayWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteVirtualGatewayResponse, error)
	DeleteVirtualGateway(ctx context.Context, body DeleteVirtualGatewayJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteVirtualGatewayResponse, error)
	// DeleteVmGroupWithBody request with arbitrary body returning *DeleteVmGroupResponse
	DeleteVmGroupWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteVmGroupResponse, error)
	DeleteVmGroup(ctx context.Context, body DeleteVmGroupJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteVmGroupResponse, error)
	// DeleteVmTemplateWithBody request with arbitrary body returning *DeleteVmTemplateResponse
	DeleteVmTemplateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteVmTemplateResponse, error)
	DeleteVmTemplate(ctx context.Context, body DeleteVmTemplateJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteVmTemplateResponse, error)
	// DeleteVmsWithBody request with arbitrary body returning *DeleteVmsResponse
	DeleteVmsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteVmsResponse, error)
	DeleteVms(ctx context.Context, body DeleteVmsJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteVmsResponse, error)
	// DeleteVolumeWithBody request with arbitrary body returning *DeleteVolumeResponse
	DeleteVolumeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteVolumeResponse, error)
	DeleteVolume(ctx context.Context, body DeleteVolumeJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteVolumeResponse, error)
	// DeleteVpnConnectionWithBody request with arbitrary body returning *DeleteVpnConnectionResponse
	DeleteVpnConnectionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteVpnConnectionResponse, error)
	DeleteVpnConnection(ctx context.Context, body DeleteVpnConnectionJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteVpnConnectionResponse, error)
	// DeleteVpnConnectionRouteWithBody request with arbitrary body returning *DeleteVpnConnectionRouteResponse
	DeleteVpnConnectionRouteWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeleteVpnConnectionRouteResponse, error)
	DeleteVpnConnectionRoute(ctx context.Context, body DeleteVpnConnectionRouteJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeleteVpnConnectionRouteResponse, error)
	// DeregisterVmsInLoadBalancerWithBody request with arbitrary body returning *DeregisterVmsInLoadBalancerResponse
	DeregisterVmsInLoadBalancerWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DeregisterVmsInLoadBalancerResponse, error)
	DeregisterVmsInLoadBalancer(ctx context.Context, body DeregisterVmsInLoadBalancerJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DeregisterVmsInLoadBalancerResponse, error)
	// DisableOutscaleLoginWithBody request with arbitrary body returning *DisableOutscaleLoginResponse
	DisableOutscaleLoginWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DisableOutscaleLoginResponse, error)
	DisableOutscaleLogin(ctx context.Context, body DisableOutscaleLoginJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DisableOutscaleLoginResponse, error)
	// DisableOutscaleLoginForUsersWithBody request with arbitrary body returning *DisableOutscaleLoginResponse
	DisableOutscaleLoginForUsersWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DisableOutscaleLoginResponse, error)
	DisableOutscaleLoginForUsers(ctx context.Context, body DisableOutscaleLoginForUsersJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DisableOutscaleLoginResponse, error)
	// DisableOutscaleLoginPerUsersWithBody request with arbitrary body returning *DisableOutscaleLoginPerUsersResponse
	DisableOutscaleLoginPerUsersWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*DisableOutscaleLoginPerUsersResponse, error)
	DisableOutscaleLoginPerUsers(ctx context.Context, body DisableOutscaleLoginPerUsersJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*DisableOutscaleLoginPerUsersResponse, error)
	// EnableOutscaleLoginWithBody request with arbitrary body returning *EnableOutscaleLoginResponse
	EnableOutscaleLoginWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*EnableOutscaleLoginResponse, error)
	EnableOutscaleLogin(ctx context.Context, body EnableOutscaleLoginJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*EnableOutscaleLoginResponse, error)
	// EnableOutscaleLoginForUsersWithBody request with arbitrary body returning *EnableOutscaleLoginForUsersResponse
	EnableOutscaleLoginForUsersWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*EnableOutscaleLoginForUsersResponse, error)
	EnableOutscaleLoginForUsers(ctx context.Context, body EnableOutscaleLoginForUsersJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*EnableOutscaleLoginForUsersResponse, error)
	// EnableOutscaleLoginPerUsersWithBody request with arbitrary body returning *EnableOutscaleLoginPerUsersResponse
	EnableOutscaleLoginPerUsersWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*EnableOutscaleLoginPerUsersResponse, error)
	EnableOutscaleLoginPerUsers(ctx context.Context, body EnableOutscaleLoginPerUsersJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*EnableOutscaleLoginPerUsersResponse, error)
	// LinkFlexibleGpuWithBody request with arbitrary body returning *LinkFlexibleGpuResponse
	LinkFlexibleGpuWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*LinkFlexibleGpuResponse, error)
	LinkFlexibleGpu(ctx context.Context, body LinkFlexibleGpuJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*LinkFlexibleGpuResponse, error)
	// LinkInternetServiceWithBody request with arbitrary body returning *LinkInternetServiceResponse
	LinkInternetServiceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*LinkInternetServiceResponse, error)
	LinkInternetService(ctx context.Context, body LinkInternetServiceJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*LinkInternetServiceResponse, error)
	// LinkLoadBalancerBackendMachinesWithBody request with arbitrary body returning *LinkLoadBalancerBackendMachinesResponse
	LinkLoadBalancerBackendMachinesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*LinkLoadBalancerBackendMachinesResponse, error)
	LinkLoadBalancerBackendMachines(ctx context.Context, body LinkLoadBalancerBackendMachinesJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*LinkLoadBalancerBackendMachinesResponse, error)
	// LinkManagedPolicyToUserGroupWithBody request with arbitrary body returning *LinkManagedPolicyToUserGroupResponse
	LinkManagedPolicyToUserGroupWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*LinkManagedPolicyToUserGroupResponse, error)
	LinkManagedPolicyToUserGroup(ctx context.Context, body LinkManagedPolicyToUserGroupJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*LinkManagedPolicyToUserGroupResponse, error)
	// LinkNicWithBody request with arbitrary body returning *LinkNicResponse
	LinkNicWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*LinkNicResponse, error)
	LinkNic(ctx context.Context, body LinkNicJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*LinkNicResponse, error)
	// LinkPolicyWithBody request with arbitrary body returning *LinkPolicyResponse
	LinkPolicyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*LinkPolicyResponse, error)
	LinkPolicy(ctx context.Context, body LinkPolicyJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*LinkPolicyResponse, error)
	// LinkPrivateIpsWithBody request with arbitrary body returning *LinkPrivateIpsResponse
	LinkPrivateIpsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*LinkPrivateIpsResponse, error)
	LinkPrivateIps(ctx context.Context, body LinkPrivateIpsJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*LinkPrivateIpsResponse, error)
	// LinkPublicIpWithBody request with arbitrary body returning *LinkPublicIpResponse
	LinkPublicIpWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*LinkPublicIpResponse, error)
	LinkPublicIp(ctx context.Context, body LinkPublicIpJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*LinkPublicIpResponse, error)
	// LinkRouteTableWithBody request with arbitrary body returning *LinkRouteTableResponse
	LinkRouteTableWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*LinkRouteTableResponse, error)
	LinkRouteTable(ctx context.Context, body LinkRouteTableJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*LinkRouteTableResponse, error)
	// LinkVirtualGatewayWithBody request with arbitrary body returning *LinkVirtualGatewayResponse
	LinkVirtualGatewayWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*LinkVirtualGatewayResponse, error)
	LinkVirtualGateway(ctx context.Context, body LinkVirtualGatewayJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*LinkVirtualGatewayResponse, error)
	// LinkVolumeWithBody request with arbitrary body returning *LinkVolumeResponse
	LinkVolumeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*LinkVolumeResponse, error)
	LinkVolume(ctx context.Context, body LinkVolumeJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*LinkVolumeResponse, error)
	// PutUserGroupPolicyWithBody request with arbitrary body returning *PutUserGroupPolicyResponse
	PutUserGroupPolicyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*PutUserGroupPolicyResponse, error)
	PutUserGroupPolicy(ctx context.Context, body PutUserGroupPolicyJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*PutUserGroupPolicyResponse, error)
	// PutUserPolicyWithBody request with arbitrary body returning *PutUserPolicyResponse
	PutUserPolicyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*PutUserPolicyResponse, error)
	PutUserPolicy(ctx context.Context, body PutUserPolicyJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*PutUserPolicyResponse, error)
	// ReadAccessKeysWithBody request with arbitrary body returning *ReadAccessKeysResponse
	ReadAccessKeysWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadAccessKeysResponse, error)
	ReadAccessKeys(ctx context.Context, body ReadAccessKeysJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadAccessKeysResponse, error)
	// ReadAccountsWithBody request with arbitrary body returning *ReadAccountsResponse
	ReadAccountsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadAccountsResponse, error)
	ReadAccounts(ctx context.Context, body ReadAccountsJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadAccountsResponse, error)
	// ReadAdminPasswordWithBody request with arbitrary body returning *ReadAdminPasswordResponse
	ReadAdminPasswordWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadAdminPasswordResponse, error)
	ReadAdminPassword(ctx context.Context, body ReadAdminPasswordJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadAdminPasswordResponse, error)
	// ReadApiAccessPolicyWithBody request with arbitrary body returning *ReadApiAccessPolicyResponse
	ReadApiAccessPolicyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadApiAccessPolicyResponse, error)
	ReadApiAccessPolicy(ctx context.Context, body ReadApiAccessPolicyJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadApiAccessPolicyResponse, error)
	// ReadApiAccessRulesWithBody request with arbitrary body returning *ReadApiAccessRulesResponse
	ReadApiAccessRulesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadApiAccessRulesResponse, error)
	ReadApiAccessRules(ctx context.Context, body ReadApiAccessRulesJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadApiAccessRulesResponse, error)
	// ReadApiLogsWithBody request with arbitrary body returning *ReadApiLogsResponse
	ReadApiLogsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadApiLogsResponse, error)
	ReadApiLogs(ctx context.Context, body ReadApiLogsJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadApiLogsResponse, error)
	// ReadCasWithBody request with arbitrary body returning *ReadCasResponse
	ReadCasWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadCasResponse, error)
	ReadCas(ctx context.Context, body ReadCasJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadCasResponse, error)
	// ReadCatalogWithBody request with arbitrary body returning *ReadCatalogResponse
	ReadCatalogWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadCatalogResponse, error)
	ReadCatalog(ctx context.Context, body ReadCatalogJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadCatalogResponse, error)
	// ReadCatalogsWithBody request with arbitrary body returning *ReadCatalogsResponse
	ReadCatalogsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadCatalogsResponse, error)
	ReadCatalogs(ctx context.Context, body ReadCatalogsJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadCatalogsResponse, error)
	// ReadClientGatewaysWithBody request with arbitrary body returning *ReadClientGatewaysResponse
	ReadClientGatewaysWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadClientGatewaysResponse, error)
	ReadClientGateways(ctx context.Context, body ReadClientGatewaysJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadClientGatewaysResponse, error)
	// ReadConsoleOutputWithBody request with arbitrary body returning *ReadConsoleOutputResponse
	ReadConsoleOutputWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadConsoleOutputResponse, error)
	ReadConsoleOutput(ctx context.Context, body ReadConsoleOutputJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadConsoleOutputResponse, error)
	// ReadConsumptionAccountWithBody request with arbitrary body returning *ReadConsumptionAccountResponse
	ReadConsumptionAccountWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadConsumptionAccountResponse, error)
	ReadConsumptionAccount(ctx context.Context, body ReadConsumptionAccountJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadConsumptionAccountResponse, error)
	// ReadDedicatedGroupsWithBody request with arbitrary body returning *ReadDedicatedGroupsResponse
	ReadDedicatedGroupsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadDedicatedGroupsResponse, error)
	ReadDedicatedGroups(ctx context.Context, body ReadDedicatedGroupsJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadDedicatedGroupsResponse, error)
	// ReadDhcpOptionsWithBody request with arbitrary body returning *ReadDhcpOptionsResponse
	ReadDhcpOptionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadDhcpOptionsResponse, error)
	ReadDhcpOptions(ctx context.Context, body ReadDhcpOptionsJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadDhcpOptionsResponse, error)
	// ReadDirectLinkInterfacesWithBody request with arbitrary body returning *ReadDirectLinkInterfacesResponse
	ReadDirectLinkInterfacesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadDirectLinkInterfacesResponse, error)
	ReadDirectLinkInterfaces(ctx context.Context, body ReadDirectLinkInterfacesJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadDirectLinkInterfacesResponse, error)
	// ReadDirectLinksWithBody request with arbitrary body returning *ReadDirectLinksResponse
	ReadDirectLinksWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadDirectLinksResponse, error)
	ReadDirectLinks(ctx context.Context, body ReadDirectLinksJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadDirectLinksResponse, error)
	// ReadEntitiesLinkedToPolicyWithBody request with arbitrary body returning *ReadEntitiesLinkedToPolicyResponse
	ReadEntitiesLinkedToPolicyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadEntitiesLinkedToPolicyResponse, error)
	ReadEntitiesLinkedToPolicy(ctx context.Context, body ReadEntitiesLinkedToPolicyJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadEntitiesLinkedToPolicyResponse, error)
	// ReadFlexibleGpuCatalogWithBody request with arbitrary body returning *ReadFlexibleGpuCatalogResponse
	ReadFlexibleGpuCatalogWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadFlexibleGpuCatalogResponse, error)
	ReadFlexibleGpuCatalog(ctx context.Context, body ReadFlexibleGpuCatalogJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadFlexibleGpuCatalogResponse, error)
	// ReadFlexibleGpusWithBody request with arbitrary body returning *ReadFlexibleGpusResponse
	ReadFlexibleGpusWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadFlexibleGpusResponse, error)
	ReadFlexibleGpus(ctx context.Context, body ReadFlexibleGpusJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadFlexibleGpusResponse, error)
	// ReadImageExportTasksWithBody request with arbitrary body returning *ReadImageExportTasksResponse
	ReadImageExportTasksWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadImageExportTasksResponse, error)
	ReadImageExportTasks(ctx context.Context, body ReadImageExportTasksJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadImageExportTasksResponse, error)
	// ReadImagesWithBody request with arbitrary body returning *ReadImagesResponse
	ReadImagesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadImagesResponse, error)
	ReadImages(ctx context.Context, body ReadImagesJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadImagesResponse, error)
	// ReadInternetServicesWithBody request with arbitrary body returning *ReadInternetServicesResponse
	ReadInternetServicesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadInternetServicesResponse, error)
	ReadInternetServices(ctx context.Context, body ReadInternetServicesJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadInternetServicesResponse, error)
	// ReadKeypairsWithBody request with arbitrary body returning *ReadKeypairsResponse
	ReadKeypairsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadKeypairsResponse, error)
	ReadKeypairs(ctx context.Context, body ReadKeypairsJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadKeypairsResponse, error)
	// ReadLinkedPoliciesWithBody request with arbitrary body returning *ReadLinkedPoliciesResponse
	ReadLinkedPoliciesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadLinkedPoliciesResponse, error)
	ReadLinkedPolicies(ctx context.Context, body ReadLinkedPoliciesJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadLinkedPoliciesResponse, error)
	// ReadListenerRulesWithBody request with arbitrary body returning *ReadListenerRulesResponse
	ReadListenerRulesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadListenerRulesResponse, error)
	ReadListenerRules(ctx context.Context, body ReadListenerRulesJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadListenerRulesResponse, error)
	// ReadLoadBalancerTagsWithBody request with arbitrary body returning *ReadLoadBalancerTagsResponse
	ReadLoadBalancerTagsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadLoadBalancerTagsResponse, error)
	ReadLoadBalancerTags(ctx context.Context, body ReadLoadBalancerTagsJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadLoadBalancerTagsResponse, error)
	// ReadLoadBalancersWithBody request with arbitrary body returning *ReadLoadBalancersResponse
	ReadLoadBalancersWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadLoadBalancersResponse, error)
	ReadLoadBalancers(ctx context.Context, body ReadLoadBalancersJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadLoadBalancersResponse, error)
	// ReadLocationsWithBody request with arbitrary body returning *ReadLocationsResponse
	ReadLocationsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadLocationsResponse, error)
	ReadLocations(ctx context.Context, body ReadLocationsJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadLocationsResponse, error)
	// ReadManagedPoliciesLinkedToUserGroupWithBody request with arbitrary body returning *ReadManagedPoliciesLinkedToUserGroupResponse
	ReadManagedPoliciesLinkedToUserGroupWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadManagedPoliciesLinkedToUserGroupResponse, error)
	ReadManagedPoliciesLinkedToUserGroup(ctx context.Context, body ReadManagedPoliciesLinkedToUserGroupJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadManagedPoliciesLinkedToUserGroupResponse, error)
	// ReadNatServicesWithBody request with arbitrary body returning *ReadNatServicesResponse
	ReadNatServicesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadNatServicesResponse, error)
	ReadNatServices(ctx context.Context, body ReadNatServicesJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadNatServicesResponse, error)
	// ReadNetAccessPointServicesWithBody request with arbitrary body returning *ReadNetAccessPointServicesResponse
	ReadNetAccessPointServicesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadNetAccessPointServicesResponse, error)
	ReadNetAccessPointServices(ctx context.Context, body ReadNetAccessPointServicesJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadNetAccessPointServicesResponse, error)
	// ReadNetAccessPointsWithBody request with arbitrary body returning *ReadNetAccessPointsResponse
	ReadNetAccessPointsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadNetAccessPointsResponse, error)
	ReadNetAccessPoints(ctx context.Context, body ReadNetAccessPointsJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadNetAccessPointsResponse, error)
	// ReadNetPeeringsWithBody request with arbitrary body returning *ReadNetPeeringsResponse
	ReadNetPeeringsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadNetPeeringsResponse, error)
	ReadNetPeerings(ctx context.Context, body ReadNetPeeringsJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadNetPeeringsResponse, error)
	// ReadNetsWithBody request with arbitrary body returning *ReadNetsResponse
	ReadNetsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadNetsResponse, error)
	ReadNets(ctx context.Context, body ReadNetsJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadNetsResponse, error)
	// ReadNicsWithBody request with arbitrary body returning *ReadNicsResponse
	ReadNicsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadNicsResponse, error)
	ReadNics(ctx context.Context, body ReadNicsJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadNicsResponse, error)
	// ReadPoliciesWithBody request with arbitrary body returning *ReadPoliciesResponse
	ReadPoliciesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadPoliciesResponse, error)
	ReadPolicies(ctx context.Context, body ReadPoliciesJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadPoliciesResponse, error)
	// ReadPolicyWithBody request with arbitrary body returning *ReadPolicyResponse
	ReadPolicyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadPolicyResponse, error)
	ReadPolicy(ctx context.Context, body ReadPolicyJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadPolicyResponse, error)
	// ReadPolicyVersionWithBody request with arbitrary body returning *ReadPolicyVersionResponse
	ReadPolicyVersionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadPolicyVersionResponse, error)
	ReadPolicyVersion(ctx context.Context, body ReadPolicyVersionJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadPolicyVersionResponse, error)
	// ReadPolicyVersionsWithBody request with arbitrary body returning *ReadPolicyVersionsResponse
	ReadPolicyVersionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadPolicyVersionsResponse, error)
	ReadPolicyVersions(ctx context.Context, body ReadPolicyVersionsJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadPolicyVersionsResponse, error)
	// ReadProductTypesWithBody request with arbitrary body returning *ReadProductTypesResponse
	ReadProductTypesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadProductTypesResponse, error)
	ReadProductTypes(ctx context.Context, body ReadProductTypesJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadProductTypesResponse, error)
	// ReadPublicCatalogWithBody request with arbitrary body returning *ReadPublicCatalogResponse
	ReadPublicCatalogWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadPublicCatalogResponse, error)
	ReadPublicCatalog(ctx context.Context, body ReadPublicCatalogJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadPublicCatalogResponse, error)
	// ReadPublicIpRangesWithBody request with arbitrary body returning *ReadPublicIpRangesResponse
	ReadPublicIpRangesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadPublicIpRangesResponse, error)
	ReadPublicIpRanges(ctx context.Context, body ReadPublicIpRangesJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadPublicIpRangesResponse, error)
	// ReadPublicIpsWithBody request with arbitrary body returning *ReadPublicIpsResponse
	ReadPublicIpsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadPublicIpsResponse, error)
	ReadPublicIps(ctx context.Context, body ReadPublicIpsJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadPublicIpsResponse, error)
	// ReadQuotasWithBody request with arbitrary body returning *ReadQuotasResponse
	ReadQuotasWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadQuotasResponse, error)
	ReadQuotas(ctx context.Context, body ReadQuotasJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadQuotasResponse, error)
	// ReadRegionsWithBody request with arbitrary body returning *ReadRegionsResponse
	ReadRegionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadRegionsResponse, error)
	ReadRegions(ctx context.Context, body ReadRegionsJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadRegionsResponse, error)
	// ReadRouteTablesWithBody request with arbitrary body returning *ReadRouteTablesResponse
	ReadRouteTablesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadRouteTablesResponse, error)
	ReadRouteTables(ctx context.Context, body ReadRouteTablesJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadRouteTablesResponse, error)
	// ReadSecurityGroupsWithBody request with arbitrary body returning *ReadSecurityGroupsResponse
	ReadSecurityGroupsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadSecurityGroupsResponse, error)
	ReadSecurityGroups(ctx context.Context, body ReadSecurityGroupsJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadSecurityGroupsResponse, error)
	// ReadServerCertificatesWithBody request with arbitrary body returning *ReadServerCertificatesResponse
	ReadServerCertificatesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadServerCertificatesResponse, error)
	ReadServerCertificates(ctx context.Context, body ReadServerCertificatesJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadServerCertificatesResponse, error)
	// ReadSnapshotExportTasksWithBody request with arbitrary body returning *ReadSnapshotExportTasksResponse
	ReadSnapshotExportTasksWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadSnapshotExportTasksResponse, error)
	ReadSnapshotExportTasks(ctx context.Context, body ReadSnapshotExportTasksJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadSnapshotExportTasksResponse, error)
	// ReadSnapshotsWithBody request with arbitrary body returning *ReadSnapshotsResponse
	ReadSnapshotsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadSnapshotsResponse, error)
	ReadSnapshots(ctx context.Context, body ReadSnapshotsJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadSnapshotsResponse, error)
	// ReadSubnetsWithBody request with arbitrary body returning *ReadSubnetsResponse
	ReadSubnetsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadSubnetsResponse, error)
	ReadSubnets(ctx context.Context, body ReadSubnetsJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadSubnetsResponse, error)
	// ReadSubregionsWithBody request with arbitrary body returning *ReadSubregionsResponse
	ReadSubregionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadSubregionsResponse, error)
	ReadSubregions(ctx context.Context, body ReadSubregionsJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadSubregionsResponse, error)
	// ReadTagsWithBody request with arbitrary body returning *ReadTagsResponse
	ReadTagsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadTagsResponse, error)
	ReadTags(ctx context.Context, body ReadTagsJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadTagsResponse, error)
	// ReadUnitPriceWithBody request with arbitrary body returning *ReadUnitPriceResponse
	ReadUnitPriceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadUnitPriceResponse, error)
	ReadUnitPrice(ctx context.Context, body ReadUnitPriceJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadUnitPriceResponse, error)
	// ReadUserGroupWithBody request with arbitrary body returning *ReadUserGroupResponse
	ReadUserGroupWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadUserGroupResponse, error)
	ReadUserGroup(ctx context.Context, body ReadUserGroupJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadUserGroupResponse, error)
	// ReadUserGroupPoliciesWithBody request with arbitrary body returning *ReadUserGroupPoliciesResponse
	ReadUserGroupPoliciesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadUserGroupPoliciesResponse, error)
	ReadUserGroupPolicies(ctx context.Context, body ReadUserGroupPoliciesJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadUserGroupPoliciesResponse, error)
	// ReadUserGroupPolicyWithBody request with arbitrary body returning *ReadUserGroupPolicyResponse
	ReadUserGroupPolicyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadUserGroupPolicyResponse, error)
	ReadUserGroupPolicy(ctx context.Context, body ReadUserGroupPolicyJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadUserGroupPolicyResponse, error)
	// ReadUserGroupsWithBody request with arbitrary body returning *ReadUserGroupsResponse
	ReadUserGroupsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadUserGroupsResponse, error)
	ReadUserGroups(ctx context.Context, body ReadUserGroupsJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadUserGroupsResponse, error)
	// ReadUserGroupsPerUserWithBody request with arbitrary body returning *ReadUserGroupsPerUserResponse
	ReadUserGroupsPerUserWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadUserGroupsPerUserResponse, error)
	ReadUserGroupsPerUser(ctx context.Context, body ReadUserGroupsPerUserJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadUserGroupsPerUserResponse, error)
	// ReadUserPoliciesWithBody request with arbitrary body returning *ReadUserPoliciesResponse
	ReadUserPoliciesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadUserPoliciesResponse, error)
	ReadUserPolicies(ctx context.Context, body ReadUserPoliciesJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadUserPoliciesResponse, error)
	// ReadUserPolicyWithBody request with arbitrary body returning *ReadUserPolicyResponse
	ReadUserPolicyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadUserPolicyResponse, error)
	ReadUserPolicy(ctx context.Context, body ReadUserPolicyJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadUserPolicyResponse, error)
	// ReadUsersWithBody request with arbitrary body returning *ReadUsersResponse
	ReadUsersWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadUsersResponse, error)
	ReadUsers(ctx context.Context, body ReadUsersJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadUsersResponse, error)
	// ReadVirtualGatewaysWithBody request with arbitrary body returning *ReadVirtualGatewaysResponse
	ReadVirtualGatewaysWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadVirtualGatewaysResponse, error)
	ReadVirtualGateways(ctx context.Context, body ReadVirtualGatewaysJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadVirtualGatewaysResponse, error)
	// ReadVmGroupsWithBody request with arbitrary body returning *ReadVmGroupsResponse
	ReadVmGroupsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadVmGroupsResponse, error)
	ReadVmGroups(ctx context.Context, body ReadVmGroupsJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadVmGroupsResponse, error)
	// ReadVmTemplatesWithBody request with arbitrary body returning *ReadVmTemplatesResponse
	ReadVmTemplatesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadVmTemplatesResponse, error)
	ReadVmTemplates(ctx context.Context, body ReadVmTemplatesJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadVmTemplatesResponse, error)
	// ReadVmTypesWithBody request with arbitrary body returning *ReadVmTypesResponse
	ReadVmTypesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadVmTypesResponse, error)
	ReadVmTypes(ctx context.Context, body ReadVmTypesJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadVmTypesResponse, error)
	// ReadVmsWithBody request with arbitrary body returning *ReadVmsResponse
	ReadVmsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadVmsResponse, error)
	ReadVms(ctx context.Context, body ReadVmsJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadVmsResponse, error)
	// ReadVmsHealthWithBody request with arbitrary body returning *ReadVmsHealthResponse
	ReadVmsHealthWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadVmsHealthResponse, error)
	ReadVmsHealth(ctx context.Context, body ReadVmsHealthJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadVmsHealthResponse, error)
	// ReadVmsStateWithBody request with arbitrary body returning *ReadVmsStateResponse
	ReadVmsStateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadVmsStateResponse, error)
	ReadVmsState(ctx context.Context, body ReadVmsStateJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadVmsStateResponse, error)
	// ReadVolumesWithBody request with arbitrary body returning *ReadVolumesResponse
	ReadVolumesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadVolumesResponse, error)
	ReadVolumes(ctx context.Context, body ReadVolumesJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadVolumesResponse, error)
	// ReadVpnConnectionsWithBody request with arbitrary body returning *ReadVpnConnectionsResponse
	ReadVpnConnectionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ReadVpnConnectionsResponse, error)
	ReadVpnConnections(ctx context.Context, body ReadVpnConnectionsJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ReadVpnConnectionsResponse, error)
	// RebootVmsWithBody request with arbitrary body returning *RebootVmsResponse
	RebootVmsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*RebootVmsResponse, error)
	RebootVms(ctx context.Context, body RebootVmsJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*RebootVmsResponse, error)
	// RegisterVmsInLoadBalancerWithBody request with arbitrary body returning *RegisterVmsInLoadBalancerResponse
	RegisterVmsInLoadBalancerWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*RegisterVmsInLoadBalancerResponse, error)
	RegisterVmsInLoadBalancer(ctx context.Context, body RegisterVmsInLoadBalancerJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*RegisterVmsInLoadBalancerResponse, error)
	// RejectNetPeeringWithBody request with arbitrary body returning *RejectNetPeeringResponse
	RejectNetPeeringWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*RejectNetPeeringResponse, error)
	RejectNetPeering(ctx context.Context, body RejectNetPeeringJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*RejectNetPeeringResponse, error)
	// RemoveUserFromUserGroupWithBody request with arbitrary body returning *RemoveUserFromUserGroupResponse
	RemoveUserFromUserGroupWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*RemoveUserFromUserGroupResponse, error)
	RemoveUserFromUserGroup(ctx context.Context, body RemoveUserFromUserGroupJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*RemoveUserFromUserGroupResponse, error)
	// ScaleDownVmGroupWithBody request with arbitrary body returning *ScaleDownVmGroupResponse
	ScaleDownVmGroupWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ScaleDownVmGroupResponse, error)
	ScaleDownVmGroup(ctx context.Context, body ScaleDownVmGroupJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ScaleDownVmGroupResponse, error)
	// ScaleUpVmGroupWithBody request with arbitrary body returning *ScaleUpVmGroupResponse
	ScaleUpVmGroupWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ScaleUpVmGroupResponse, error)
	ScaleUpVmGroup(ctx context.Context, body ScaleUpVmGroupJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ScaleUpVmGroupResponse, error)
	// SetDefaultPolicyVersionWithBody request with arbitrary body returning *SetDefaultPolicyVersionResponse
	SetDefaultPolicyVersionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*SetDefaultPolicyVersionResponse, error)
	SetDefaultPolicyVersion(ctx context.Context, body SetDefaultPolicyVersionJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*SetDefaultPolicyVersionResponse, error)
	// StartVmsWithBody request with arbitrary body returning *StartVmsResponse
	StartVmsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*StartVmsResponse, error)
	StartVms(ctx context.Context, body StartVmsJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*StartVmsResponse, error)
	// StopVmsWithBody request with arbitrary body returning *StopVmsResponse
	StopVmsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*StopVmsResponse, error)
	StopVms(ctx context.Context, body StopVmsJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*StopVmsResponse, error)
	// UnlinkFlexibleGpuWithBody request with arbitrary body returning *UnlinkFlexibleGpuResponse
	UnlinkFlexibleGpuWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*UnlinkFlexibleGpuResponse, error)
	UnlinkFlexibleGpu(ctx context.Context, body UnlinkFlexibleGpuJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*UnlinkFlexibleGpuResponse, error)
	// UnlinkInternetServiceWithBody request with arbitrary body returning *UnlinkInternetServiceResponse
	UnlinkInternetServiceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*UnlinkInternetServiceResponse, error)
	UnlinkInternetService(ctx context.Context, body UnlinkInternetServiceJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*UnlinkInternetServiceResponse, error)
	// UnlinkLoadBalancerBackendMachinesWithBody request with arbitrary body returning *UnlinkLoadBalancerBackendMachinesResponse
	UnlinkLoadBalancerBackendMachinesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*UnlinkLoadBalancerBackendMachinesResponse, error)
	UnlinkLoadBalancerBackendMachines(ctx context.Context, body UnlinkLoadBalancerBackendMachinesJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*UnlinkLoadBalancerBackendMachinesResponse, error)
	// UnlinkManagedPolicyFromUserGroupWithBody request with arbitrary body returning *UnlinkManagedPolicyFromUserGroupResponse
	UnlinkManagedPolicyFromUserGroupWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*UnlinkManagedPolicyFromUserGroupResponse, error)
	UnlinkManagedPolicyFromUserGroup(ctx context.Context, body UnlinkManagedPolicyFromUserGroupJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*UnlinkManagedPolicyFromUserGroupResponse, error)
	// UnlinkNicWithBody request with arbitrary body returning *UnlinkNicResponse
	UnlinkNicWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*UnlinkNicResponse, error)
	UnlinkNic(ctx context.Context, body UnlinkNicJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*UnlinkNicResponse, error)
	// UnlinkPolicyWithBody request with arbitrary body returning *UnlinkPolicyResponse
	UnlinkPolicyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*UnlinkPolicyResponse, error)
	UnlinkPolicy(ctx context.Context, body UnlinkPolicyJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*UnlinkPolicyResponse, error)
	// UnlinkPrivateIpsWithBody request with arbitrary body returning *UnlinkPrivateIpsResponse
	UnlinkPrivateIpsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*UnlinkPrivateIpsResponse, error)
	UnlinkPrivateIps(ctx context.Context, body UnlinkPrivateIpsJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*UnlinkPrivateIpsResponse, error)
	// UnlinkPublicIpWithBody request with arbitrary body returning *UnlinkPublicIpResponse
	UnlinkPublicIpWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*UnlinkPublicIpResponse, error)
	UnlinkPublicIp(ctx context.Context, body UnlinkPublicIpJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*UnlinkPublicIpResponse, error)
	// UnlinkRouteTableWithBody request with arbitrary body returning *UnlinkRouteTableResponse
	UnlinkRouteTableWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*UnlinkRouteTableResponse, error)
	UnlinkRouteTable(ctx context.Context, body UnlinkRouteTableJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*UnlinkRouteTableResponse, error)
	// UnlinkVirtualGatewayWithBody request with arbitrary body returning *UnlinkVirtualGatewayResponse
	UnlinkVirtualGatewayWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*UnlinkVirtualGatewayResponse, error)
	UnlinkVirtualGateway(ctx context.Context, body UnlinkVirtualGatewayJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*UnlinkVirtualGatewayResponse, error)
	// UnlinkVolumeWithBody request with arbitrary body returning *UnlinkVolumeResponse
	UnlinkVolumeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*UnlinkVolumeResponse, error)
	UnlinkVolume(ctx context.Context, body UnlinkVolumeJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*UnlinkVolumeResponse, error)
	// UpdateAccessKeyWithBody request with arbitrary body returning *UpdateAccessKeyResponse
	UpdateAccessKeyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*UpdateAccessKeyResponse, error)
	UpdateAccessKey(ctx context.Context, body UpdateAccessKeyJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*UpdateAccessKeyResponse, error)
	// UpdateAccountWithBody request with arbitrary body returning *UpdateAccountResponse
	UpdateAccountWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*UpdateAccountResponse, error)
	UpdateAccount(ctx context.Context, body UpdateAccountJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*UpdateAccountResponse, error)
	// UpdateApiAccessPolicyWithBody request with arbitrary body returning *UpdateApiAccessPolicyResponse
	UpdateApiAccessPolicyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*UpdateApiAccessPolicyResponse, error)
	UpdateApiAccessPolicy(ctx context.Context, body UpdateApiAccessPolicyJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*UpdateApiAccessPolicyResponse, error)
	// UpdateApiAccessRuleWithBody request with arbitrary body returning *UpdateApiAccessRuleResponse
	UpdateApiAccessRuleWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*UpdateApiAccessRuleResponse, error)
	UpdateApiAccessRule(ctx context.Context, body UpdateApiAccessRuleJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*UpdateApiAccessRuleResponse, error)
	// UpdateCaWithBody request with arbitrary body returning *UpdateCaResponse
	UpdateCaWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*UpdateCaResponse, error)
	UpdateCa(ctx context.Context, body UpdateCaJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*UpdateCaResponse, error)
	// UpdateDedicatedGroupWithBody request with arbitrary body returning *UpdateDedicatedGroupResponse
	UpdateDedicatedGroupWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*UpdateDedicatedGroupResponse, error)
	UpdateDedicatedGroup(ctx context.Context, body UpdateDedicatedGroupJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*UpdateDedicatedGroupResponse, error)
	// UpdateDirectLinkInterfaceWithBody request with arbitrary body returning *UpdateDirectLinkInterfaceResponse
	UpdateDirectLinkInterfaceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*UpdateDirectLinkInterfaceResponse, error)
	UpdateDirectLinkInterface(ctx context.Context, body UpdateDirectLinkInterfaceJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*UpdateDirectLinkInterfaceResponse, error)
	// UpdateFlexibleGpuWithBody request with arbitrary body returning *UpdateFlexibleGpuResponse
	UpdateFlexibleGpuWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*UpdateFlexibleGpuResponse, error)
	UpdateFlexibleGpu(ctx context.Context, body UpdateFlexibleGpuJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*UpdateFlexibleGpuResponse, error)
	// UpdateImageWithBody request with arbitrary body returning *UpdateImageResponse
	UpdateImageWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*UpdateImageResponse, error)
	UpdateImage(ctx context.Context, body UpdateImageJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*UpdateImageResponse, error)
	// UpdateListenerRuleWithBody request with arbitrary body returning *UpdateListenerRuleResponse
	UpdateListenerRuleWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*UpdateListenerRuleResponse, error)
	UpdateListenerRule(ctx context.Context, body UpdateListenerRuleJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*UpdateListenerRuleResponse, error)
	// UpdateLoadBalancerWithBody request with arbitrary body returning *UpdateLoadBalancerResponse
	UpdateLoadBalancerWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*UpdateLoadBalancerResponse, error)
	UpdateLoadBalancer(ctx context.Context, body UpdateLoadBalancerJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*UpdateLoadBalancerResponse, error)
	// UpdateNetWithBody request with arbitrary body returning *UpdateNetResponse
	UpdateNetWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*UpdateNetResponse, error)
	UpdateNet(ctx context.Context, body UpdateNetJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*UpdateNetResponse, error)
	// UpdateNetAccessPointWithBody request with arbitrary body returning *UpdateNetAccessPointResponse
	UpdateNetAccessPointWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*UpdateNetAccessPointResponse, error)
	UpdateNetAccessPoint(ctx context.Context, body UpdateNetAccessPointJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*UpdateNetAccessPointResponse, error)
	// UpdateNicWithBody request with arbitrary body returning *UpdateNicResponse
	UpdateNicWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*UpdateNicResponse, error)
	UpdateNic(ctx context.Context, body UpdateNicJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*UpdateNicResponse, error)
	// UpdateRouteWithBody request with arbitrary body returning *UpdateRouteResponse
	UpdateRouteWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*UpdateRouteResponse, error)
	UpdateRoute(ctx context.Context, body UpdateRouteJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*UpdateRouteResponse, error)
	// UpdateRoutePropagationWithBody request with arbitrary body returning *UpdateRoutePropagationResponse
	UpdateRoutePropagationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*UpdateRoutePropagationResponse, error)
	UpdateRoutePropagation(ctx context.Context, body UpdateRoutePropagationJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*UpdateRoutePropagationResponse, error)
	// UpdateRouteTableLinkWithBody request with arbitrary body returning *UpdateRouteTableLinkResponse
	UpdateRouteTableLinkWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*UpdateRouteTableLinkResponse, error)
	UpdateRouteTableLink(ctx context.Context, body UpdateRouteTableLinkJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*UpdateRouteTableLinkResponse, error)
	// UpdateServerCertificateWithBody request with arbitrary body returning *UpdateServerCertificateResponse
	UpdateServerCertificateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*UpdateServerCertificateResponse, error)
	UpdateServerCertificate(ctx context.Context, body UpdateServerCertificateJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*UpdateServerCertificateResponse, error)
	// UpdateSnapshotWithBody request with arbitrary body returning *UpdateSnapshotResponse
	UpdateSnapshotWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*UpdateSnapshotResponse, error)
	UpdateSnapshot(ctx context.Context, body UpdateSnapshotJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*UpdateSnapshotResponse, error)
	// UpdateSubnetWithBody request with arbitrary body returning *UpdateSubnetResponse
	UpdateSubnetWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*UpdateSubnetResponse, error)
	UpdateSubnet(ctx context.Context, body UpdateSubnetJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*UpdateSubnetResponse, error)
	// UpdateUserWithBody request with arbitrary body returning *UpdateUserResponse
	UpdateUserWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*UpdateUserResponse, error)
	UpdateUser(ctx context.Context, body UpdateUserJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*UpdateUserResponse, error)
	// UpdateUserGroupWithBody request with arbitrary body returning *UpdateUserGroupResponse
	UpdateUserGroupWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*UpdateUserGroupResponse, error)
	UpdateUserGroup(ctx context.Context, body UpdateUserGroupJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*UpdateUserGroupResponse, error)
	// UpdateVmWithBody request with arbitrary body returning *UpdateVmResponse
	UpdateVmWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*UpdateVmResponse, error)
	UpdateVm(ctx context.Context, body UpdateVmJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*UpdateVmResponse, error)
	// UpdateVmGroupWithBody request with arbitrary body returning *UpdateVmGroupResponse
	UpdateVmGroupWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*UpdateVmGroupResponse, error)
	UpdateVmGroup(ctx context.Context, body UpdateVmGroupJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*UpdateVmGroupResponse, error)
	// UpdateVmTemplateWithBody request with arbitrary body returning *UpdateVmTemplateResponse
	UpdateVmTemplateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*UpdateVmTemplateResponse, error)
	UpdateVmTemplate(ctx context.Context, body UpdateVmTemplateJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*UpdateVmTemplateResponse, error)
	// UpdateVolumeWithBody request with arbitrary body returning *UpdateVolumeResponse
	UpdateVolumeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*UpdateVolumeResponse, error)
	UpdateVolume(ctx context.Context, body UpdateVolumeJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*UpdateVolumeResponse, error)
	// UpdateVpnConnectionWithBody request with arbitrary body returning *UpdateVpnConnectionResponse
	UpdateVpnConnectionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*UpdateVpnConnectionResponse, error)
	UpdateVpnConnection(ctx context.Context, body UpdateVpnConnectionJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*UpdateVpnConnectionResponse, error)
}
