// Code generated by ifacemaker; DO NOT EDIT.

package oks

import (
	"context"
	"io"

	"github.com/outscale/osc-sdk-go/v3/internal/middleware"
)

// Interface ...
type Interface interface {
	// ListClustersByProjectID request returning *ClusterResponseList
	ListClustersByProjectID(ctx context.Context, params *ListClustersByProjectIDParams, reqEditors ...middleware.MiddlewareChainOption) (*ClusterResponseList, error)
	// CreateClusterWithBody request with arbitrary body returning *ClusterResponse
	CreateClusterWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ClusterResponse, error)
	CreateCluster(ctx context.Context, body CreateClusterJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ClusterResponse, error)
	// ListAllClusters request returning *ClusterResponseList
	ListAllClusters(ctx context.Context, params *ListAllClustersParams, reqEditors ...middleware.MiddlewareChainOption) (*ClusterResponseList, error)
	// GetControlPlanePlans request returning *ControlPlanesResponse
	GetControlPlanePlans(ctx context.Context, reqEditors ...middleware.MiddlewareChainOption) (*ControlPlanesResponse, error)
	// GetCPSubregions request returning *CPSubregionsResponse
	GetCPSubregions(ctx context.Context, reqEditors ...middleware.MiddlewareChainOption) (*CPSubregionsResponse, error)
	// GetKubernetesVersions request returning *KubernetesVersionsResponse
	GetKubernetesVersions(ctx context.Context, reqEditors ...middleware.MiddlewareChainOption) (*KubernetesVersionsResponse, error)
	// DeleteCluster request returning *DetailResponse
	DeleteCluster(ctx context.Context, clusterId string, reqEditors ...middleware.MiddlewareChainOption) (*DetailResponse, error)
	// GetCluster request returning *ClusterResponse
	GetCluster(ctx context.Context, clusterId string, reqEditors ...middleware.MiddlewareChainOption) (*ClusterResponse, error)
	// UpdateClusterWithBody request with arbitrary body returning *ClusterResponse
	UpdateClusterWithBody(ctx context.Context, clusterId string, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ClusterResponse, error)
	UpdateCluster(ctx context.Context, clusterId string, body UpdateClusterJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ClusterResponse, error)
	// GetKubeconfig request returning *KubeconfigResponse
	GetKubeconfig(ctx context.Context, clusterId string, params *GetKubeconfigParams, reqEditors ...middleware.MiddlewareChainOption) (*KubeconfigResponse, error)
	// GetKubeconfigWithPubkeyNACL request returning *KubeconfigResponse
	GetKubeconfigWithPubkeyNACL(ctx context.Context, clusterId string, params *GetKubeconfigWithPubkeyNACLParams, reqEditors ...middleware.MiddlewareChainOption) (*KubeconfigResponse, error)
	// UpgradeCluster request returning *ClusterResponse
	UpgradeCluster(ctx context.Context, clusterId string, reqEditors ...middleware.MiddlewareChainOption) (*ClusterResponse, error)
	// ListProjects request returning *ProjectResponseList
	ListProjects(ctx context.Context, params *ListProjectsParams, reqEditors ...middleware.MiddlewareChainOption) (*ProjectResponseList, error)
	// CreateProjectWithBody request with arbitrary body returning *ProjectResponse
	CreateProjectWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ProjectResponse, error)
	CreateProject(ctx context.Context, body CreateProjectJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ProjectResponse, error)
	// DeleteProject request returning *DetailResponse
	DeleteProject(ctx context.Context, projectId string, reqEditors ...middleware.MiddlewareChainOption) (*DetailResponse, error)
	// GetProject request returning *ProjectResponse
	GetProject(ctx context.Context, projectId string, reqEditors ...middleware.MiddlewareChainOption) (*ProjectResponse, error)
	// UpdateProjectWithBody request with arbitrary body returning *ProjectResponse
	UpdateProjectWithBody(ctx context.Context, projectId string, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*ProjectResponse, error)
	UpdateProject(ctx context.Context, projectId string, body UpdateProjectJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*ProjectResponse, error)
	// GetProjectPublicIps request returning *PublicIpsResponse
	GetProjectPublicIps(ctx context.Context, projectId string, reqEditors ...middleware.MiddlewareChainOption) (*PublicIpsResponse, error)
	// GetProjectQuotas request returning *ProjectsProjectSchemaQuotasResponse
	GetProjectQuotas(ctx context.Context, projectId string, reqEditors ...middleware.MiddlewareChainOption) (*ProjectsProjectSchemaQuotasResponse, error)
	// GetProjectSnapshots request returning *SnapshotsResponse
	GetProjectSnapshots(ctx context.Context, projectId string, reqEditors ...middleware.MiddlewareChainOption) (*SnapshotsResponse, error)
	// GetQuotas request returning *QuotasQuotaSchemaQuotasResponse
	GetQuotas(ctx context.Context, reqEditors ...middleware.MiddlewareChainOption) (*QuotasQuotaSchemaQuotasResponse, error)
	// GetClusterTemplate request returning *TemplateResponseClusterInputTemplate
	GetClusterTemplate(ctx context.Context, params *GetClusterTemplateParams, reqEditors ...middleware.MiddlewareChainOption) (*TemplateResponseClusterInputTemplate, error)
	// GetNodepoolTemplate request returning *TemplateResponseNodepool
	GetNodepoolTemplate(ctx context.Context, reqEditors ...middleware.MiddlewareChainOption) (*TemplateResponseNodepool, error)
	// GetProjectTemplate request returning *TemplateResponseProjectInput
	GetProjectTemplate(ctx context.Context, reqEditors ...middleware.MiddlewareChainOption) (*TemplateResponseProjectInput, error)
}
