/*
 * 3DS OUTSCALE API
 *
 * Welcome to the OUTSCALE API documentation.<br /> The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br /> You can learn more about errors returned by the API in the dedicated [errors page](api/errors).<br /><br /> Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but there are [differences in resource names](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html) between AWS and the OUTSCALE API.<br /> You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.<br /><br /> An OpenAPI description of the OUTSCALE API is also available in this [GitHub repository](https://github.com/outscale/osc-api).
 *
 * API version: 1.24
 * Contact: support@outscale.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package osc

// ConsumptionEntry Information about the resources consumed during the specified time period.
type ConsumptionEntry struct {
	// The ID of your TINA account.
	AccountId string `json:"AccountId,omitempty"`
	// The category of the resource (for example, `network`).
	Category string `json:"Category,omitempty"`
	// The beginning of the time period.
	FromDate string `json:"FromDate,omitempty"`
	// The API call that triggered the resource consumption (for example, `RunInstances` or `CreateVolume`).
	Operation string `json:"Operation,omitempty"`
	// The ID of the TINA account which is billed for your consumption. It can be different from your account in the `AccountId` parameter.
	PayingAccountId string `json:"PayingAccountId,omitempty"`
	// The service of the API call (`TinaOS-FCU`, `TinaOS-LBU`, `TinaOS-DirectLink`, `TinaOS-OOS`, or `TinaOS-OSU`).
	Service string `json:"Service,omitempty"`
	// The name of the Subregion.
	SubregionName string `json:"SubregionName,omitempty"`
	// A description of the consumed resource.
	Title string `json:"Title,omitempty"`
	// The end of the time period.
	ToDate string `json:"ToDate,omitempty"`
	// The type of resource, depending on the API call.
	Type string `json:"Type,omitempty"`
	// The consumed amount for the resource. The unit depends on the resource type. For more information, see the `Title` element.
	Value float64 `json:"Value,omitempty"`
}
