/*
 * 3DS OUTSCALE API
 *
 * Welcome to the OUTSCALE API documentation.<br /> The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br /> You can learn more about errors returned by the API in the dedicated [errors page](api/errors).<br /><br /> Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but there are [differences in resource names](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html) between AWS and the OUTSCALE API.<br /> You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.<br /><br /> An OpenAPI description of the OUTSCALE API is also available in this [GitHub repository](https://github.com/outscale/osc-api).
 *
 * API version: 1.26
 * Contact: support@outscale.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package osc

// NatService Information about the NAT service.
type NatService struct {
	// The ID of the NAT service.
	NatServiceId string `json:"NatServiceId,omitempty"`
	// The ID of the Net in which the NAT service is.
	NetId string `json:"NetId,omitempty"`
	// Information about the public IP or IPs associated with the NAT service.
	PublicIps []PublicIpLight `json:"PublicIps,omitempty"`
	// The state of the NAT service (`pending` \\| `available` \\| `deleting` \\| `deleted`).
	State string `json:"State,omitempty"`
	// The ID of the Subnet in which the NAT service is.
	SubnetId string `json:"SubnetId,omitempty"`
	// One or more tags associated with the NAT service.
	Tags []ResourceTag `json:"Tags,omitempty"`
}
