/*
 * 3DS OUTSCALE API
 *
 * Welcome to the OUTSCALE API documentation.<br /> The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br /> You can learn more about errors returned by the API in the dedicated [errors page](api/errors).<br /><br /> Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but there are [differences in resource names](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html) between AWS and the OUTSCALE API.<br /> You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.
 *
 * API version: 1.20
 * Contact: support@outscale.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package osc

// PublicIp Information about the public IP.
type PublicIp struct {
	// (Required in a Net) The ID representing the association of the public IP with the VM or the NIC.
	LinkPublicIpId string `json:"LinkPublicIpId,omitempty"`
	// The account ID of the owner of the NIC.
	NicAccountId string `json:"NicAccountId,omitempty"`
	// The ID of the NIC the public IP is associated with (if any).
	NicId string `json:"NicId,omitempty"`
	// The private IP associated with the public IP.
	PrivateIp string `json:"PrivateIp,omitempty"`
	// The public IP.
	PublicIp string `json:"PublicIp,omitempty"`
	// The allocation ID of the public IP.
	PublicIpId string `json:"PublicIpId,omitempty"`
	// One or more tags associated with the public IP.
	Tags []ResourceTag `json:"Tags,omitempty"`
	// The ID of the VM the public IP is associated with (if any).
	VmId string `json:"VmId,omitempty"`
}
