/*
 * 3DS OUTSCALE API
 *
 * Welcome to the OUTSCALE API documentation.<br /> The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br /> You can learn more about errors returned by the API in the dedicated [errors page](api/errors).<br /><br /> Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but there are [differences in resource names](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html) between AWS and the OUTSCALE API.<br /> You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.<br /><br /> An OpenAPI description of the OUTSCALE API is also available in this [GitHub repository](https://github.com/outscale/osc-api).
 *
 * API version: 1.26
 * Contact: support@outscale.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package osc

// CreateListenerRuleRequest struct for CreateListenerRuleRequest
type CreateListenerRuleRequest struct {
	// If true, checks whether you have the required permissions to perform the action.
	DryRun       bool                    `json:"DryRun,omitempty"`
	Listener     LoadBalancerLight       `json:"Listener"`
	ListenerRule ListenerRuleForCreation `json:"ListenerRule"`
	// The IDs of the backend VMs.
	VmIds []string `json:"VmIds"`
}
