/*
 * 3DS OUTSCALE API
 *
 * Welcome to the OUTSCALE API documentation.<br /> The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br /> You can learn more about errors returned by the API in the dedicated [errors page](api/errors).<br /><br /> Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but there are [differences in resource names](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html) between AWS and the OUTSCALE API.<br /> You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.
 *
 * API version: 1.21
 * Contact: support@outscale.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package osc

// FiltersSubnet One or more filters.
type FiltersSubnet struct {
	// The number of available IPs.
	AvailableIpsCounts []int32 `json:"AvailableIpsCounts,omitempty"`
	// The IP ranges in the Subnets, in CIDR notation (for example, `10.0.0.0/16`).
	IpRanges []string `json:"IpRanges,omitempty"`
	// The IDs of the Nets in which the Subnets are.
	NetIds []string `json:"NetIds,omitempty"`
	// The states of the Subnets (`pending` \\| `available` \\| `deleted`).
	States []string `json:"States,omitempty"`
	// The IDs of the Subnets.
	SubnetIds []string `json:"SubnetIds,omitempty"`
	// The names of the Subregions in which the Subnets are located.
	SubregionNames []string `json:"SubregionNames,omitempty"`
	// The keys of the tags associated with the Subnets.
	TagKeys []string `json:"TagKeys,omitempty"`
	// The values of the tags associated with the Subnets.
	TagValues []string `json:"TagValues,omitempty"`
	// The key/value combination of the tags associated with the Subnets, in the following format: &quot;Filters&quot;:{&quot;Tags&quot;:[&quot;TAGKEY=TAGVALUE&quot;]}.
	Tags []string `json:"Tags,omitempty"`
}
