/*
 * 3DS OUTSCALE API
 *
 * Welcome to the OUTSCALE API documentation.<br /><br />  The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br />  Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but some resources have different names in AWS than in the OUTSCALE API. You can find a list of the differences [here](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html).<br /><br />  You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.
 *
 * API version: 1.18
 * Contact: support@outscale.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package osc

// PublicIp Information about the public IP.
type PublicIp struct {
	// (Required in a Net) The ID representing the association of the public IP with the VM or the NIC.
	LinkPublicIpId string `json:"LinkPublicIpId,omitempty"`
	// The account ID of the owner of the NIC.
	NicAccountId string `json:"NicAccountId,omitempty"`
	// The ID of the NIC the public IP is associated with (if any).
	NicId string `json:"NicId,omitempty"`
	// The private IP associated with the public IP.
	PrivateIp string `json:"PrivateIp,omitempty"`
	// The public IP.
	PublicIp string `json:"PublicIp,omitempty"`
	// The allocation ID of the public IP.
	PublicIpId string `json:"PublicIpId,omitempty"`
	// One or more tags associated with the public IP.
	Tags []ResourceTag `json:"Tags,omitempty"`
	// The ID of the VM the public IP is associated with (if any).
	VmId string `json:"VmId,omitempty"`
}
