/*
 * 3DS OUTSCALE API
 *
 * Welcome to the OUTSCALE API documentation.<br /> The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br /> You can learn more about errors returned by the API in the dedicated [errors page](api/errors).<br /><br /> Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but there are [differences in resource names](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html) between AWS and the OUTSCALE API.<br /> You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.
 *
 * API version: 1.21
 * Contact: support@outscale.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package osc

// FiltersVmsState One or more filters.
type FiltersVmsState struct {
	// The code for the scheduled event (`system-reboot` \\| `system-maintenance`).
	MaintenanceEventCodes []string `json:"MaintenanceEventCodes,omitempty"`
	// The description of the scheduled event.
	MaintenanceEventDescriptions []string `json:"MaintenanceEventDescriptions,omitempty"`
	// The latest time the event can end.
	MaintenanceEventsNotAfter []string `json:"MaintenanceEventsNotAfter,omitempty"`
	// The earliest time the event can start.
	MaintenanceEventsNotBefore []string `json:"MaintenanceEventsNotBefore,omitempty"`
	// The names of the Subregions of the VMs.
	SubregionNames []string `json:"SubregionNames,omitempty"`
	// One or more IDs of VMs.
	VmIds []string `json:"VmIds,omitempty"`
	// The states of the VMs (`pending` \\| `running` \\| `stopping` \\| `stopped` \\| `shutting-down` \\| `terminated` \\| `quarantine`).
	VmStates []string `json:"VmStates,omitempty"`
}
