name: osc-sdk-go release build

on:
  workflow_dispatch:
    inputs:
      api_version:
        description: 'Outscale API version'
        required: true

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  auto-build-v2:
    environment: auto-build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: v2
      - uses: chainguard-dev/actions/setup-gitsign@main

      - name: Set up Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6
        with:
          go-version: 1.25

      - name: Write Outscale API version to use
        run: echo "${{ github.event.inputs.api_version }}" > api_version
      - name: auto-generate release
        run: make release-build

      - name: Get SDK version
        id: get-sdk-version
        run: |
          echo "sdk_version=$(cat ./sdk_version)" >> "$GITHUB_OUTPUT"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          committer: "Outscale Bot <opensource+bot@outscale.com>"
          author: "Outscale Bot <opensource+bot@outscale.com>"
          commit-message: "🔖 release: osc-sdk-go v${{ env.sdk_version }}"
          body: |
            Automatic build of SDK v${{ env.sdk_version }} version based on Outscale API ${{ env.api_version }}.
          title: "SDK v${{ env.sdk_version }}"
          token: "${{ env.token }}"
        env:
          sdk_version: ${{ steps.get-sdk-version.outputs.sdk_version }}
          api_version: ${{ github.event.inputs.api_version }}
          token: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
