name: osc-sdk-go release build
on:
  workflow_dispatch:
    inputs:
      api_version:
        description: 'Outscale API version'
        required: true

jobs:
  auto-build-v2:
    environment: auto-build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: v2
      - name: Set up Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6
        with:
          go-version: 1.23
      - name: Write Outscale API version to use
        run: echo "${{ github.event.inputs.api_version }}" > api_version
      - name: check for release duplicate
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: make release-check-duplicate
      - name: auto-generate release
        run: make release-build
      - name: push release branch
        run: make release-push
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: create pull request
        run: make release-pr
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
