name: Github sanity scanner

on:
  pull_request:
    branches: [ v2 ]

permissions:
  contents: read

jobs:
  github-sanity-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Github sanity scanner
      uses: outscale/github-sanity-scan@380a9927b4be45d9c4f6f66a4e8dfd7cf7b18513 # main
      with:
        no-pull-request-target: true
