name: pull-request-v3

on:
  pull_request:
    branches: [ v3 ]
    
jobs:
  reuse-test:
    runs-on: ubuntu-24.04
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: 🔎 Reuse check
        run: |
          docker run --rm --volume $PWD:/data fsfe/reuse:5.1 lint
  examples-test:
    runs-on: [self-hosted, linux, eu-west-2]
    steps:
      - name: 🧹 Frieza
        uses: outscale/frieza-github-actions/frieza-clean@master
        with:
          access_key: ${{ secrets.OSC_ACCESS_KEY }}
          secret_key: ${{ secrets.OSC_SECRET_KEY }}
          region: ${{ secrets.OSC_REGION }}
      - name: ⬇️ Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: ⬇️ Install Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: 1.24
      - name: 🧪 Tests
        env:
          OSC_ACCESS_KEY: ${{ secrets.OSC_ACCESS_KEY }}
          OSC_SECRET_KEY: ${{ secrets.OSC_SECRET_KEY }}
          OSC_REGION: ${{ secrets.OSC_REGION }}
          OMI_ID: ${{ secrets.OMI_ID }}
        run: make test
  regeneration-test:
    runs-on: ubuntu-24.04
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: ⬇️ Install Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: 1.24
      - name: 🧪 SDK re-generation test
        run: |
            make gen
            git diff --exit-code
