name: pull-request-v3

on:
  pull_request:
    branches: [v3]

permissions:
  contents: read
  id-token: write

jobs:
  lint-test:
    runs-on: ubuntu-24.04
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: ⬇️ Install Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: 'go.mod'
      - name: 🔎 Lint
        uses: outscale/goutils/.github/actions/lint@main
      - name: 👮 Reuse
        run: |
          docker run --rm --volume $PWD:/data fsfe/reuse:5.1 lint
  examples-test:
    runs-on: [authenticated, Linux]
    steps:
      - name: 🔒🧹 Setup Vault & Frieza
        id: secrets
        uses: outscale/.github/vault-frieza-clean@eb7bd1e0360703d0ad355bce46029ae8d49bac04
        with:
          vault_role: outscale-osc-sdk-go
          osc_account: oak
      - name: ⬇️ Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: ⬇️ Install Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: 'go.mod'
      - name: 🧪 Tests
        env:
          OSC_ACCESS_KEY: ${{ steps.secrets.outputs.access_key }}
          OSC_SECRET_KEY: ${{ steps.secrets.outputs.secret_key }}
          OSC_REGION: ${{ steps.secrets.outputs.region }}
          OMI_ID: ${{ secrets.OMI_ID }}
        run: make test

  regeneration-test:
    runs-on: ubuntu-24.04
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: ⬇️ Install Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: 'go.mod'
      - name: 🧪 SDK re-generation test
        run: |
          make gen
          git diff --exit-code . ':(exclude)go.sum'
