name: pull-request-v2

on:
  pull_request:
    branches: [ v2 ]

jobs:
  reuse-test:
    runs-on: ubuntu-24.04
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: 🧪 Reuse specification test
        run: make reuse-test
  examples-test:
    runs-on: [self-hosted, linux, eu-west-2]
    steps:
      - name: 🧹 Frieza
        uses: outscale/frieza-github-actions/frieza-clean@1a8eba5199913da60ae6d92d6050e17410186a38 # main
        with:
          access_key: ${{ secrets.OSC_ACCESS_KEY }}
          secret_key: ${{ secrets.OSC_SECRET_KEY }}
          region: ${{ secrets.OSC_REGION }}
      - name: ⬇️ Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: ⬇️ Install Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: 1.25
      - name: 🧪 Tests
        env:
          OSC_ACCESS_KEY: ${{ secrets.OSC_ACCESS_KEY }}
          OSC_SECRET_KEY: ${{ secrets.OSC_SECRET_KEY }}
          OSC_REGION: ${{ secrets.OSC_REGION }}
          OMI_ID: ${{ secrets.OMI_ID }}
        run: make go-test
  regeneration-test:
    runs-on: ubuntu-24.04
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: ⬇️ Install Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: 1.25
      - name: 🧪 SDK re-generation test
        run: make regen-test
