name: pull-request-v3

on:
  pull_request:
    branches: [ v3 ]
    
jobs:
  reuse-test:
    runs-on: ubuntu-24.04
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: 🔎 Reuse check
        run: |
          docker run --rm --volume $PWD:/data fsfe/reuse:5.1 lint
  examples-test:
    runs-on: [self-hosted, linux, eu-west-2]
    steps:
      - name: 🧹 Frieza
        uses: outscale/frieza-github-actions/frieza-clean@master
        with:
          access_key: ${{ secrets.OSC_ACCESS_KEY }}
          secret_key: ${{ secrets.OSC_SECRET_KEY }}
          region: ${{ secrets.OSC_REGION }}
      - name: ⬇️ Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: ⬇️ Install Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6
        with:
          go-version: 1.26
      - name: 🧪 Tests
        env:
          OSC_ACCESS_KEY: ${{ secrets.OSC_ACCESS_KEY }}
          OSC_SECRET_KEY: ${{ secrets.OSC_SECRET_KEY }}
          OSC_REGION: ${{ secrets.OSC_REGION }}
          OMI_ID: ${{ secrets.OMI_ID }}
        run: make test
  regeneration-test:
    runs-on: ubuntu-24.04
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: ⬇️ Install Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6
        with:
          go-version: 1.26
      - name: 🧪 SDK re-generation test
        run: |
            make gen
            git diff --exit-code
